### PR TITLE
Atlas 0.2.1

### LINKED ISSUE #2: Concurrency issues
atlas has threading problems it seems. Its running into concurrent modification exceptions for getOrCreateClass on a mapping set
putting a synchronized(remapper) into the  JarEntryRemappingTransformer solves it
was wondering why I was randomly missing classes, somewhere the exception gets eaten too

### LINKED ISSUE #8: Possible to remove entries from a jar while transforming?
It doesn't seem to be possible to remove entries from a jar within a transformer as Atlas currently works -- would it be possible to allow this, by returning `null` out of a JarEntryTransformer or something similar?

This can allow stripping signature files or unnecessary libraries.

### PR DESCRIPTION
**Pull request by jamierocks**
Atlas 0.2.1 provides some quality-of-life features designed to make Atlas more configurable and accountable.

- Execeptions will no longer be dismissed when transforming, and rather rethrown (as was my intention).
- Output jars will be repackaged to ensure that the manifest is read by JarInputStream correctly.
- Atlases can specify their own ExecutorService to use, or their parallelism level if using our provided constructors.

### CODE REVIEW

File: src/main/java/org/cadixdev/atlas/Atlas.java [hunk 1]
```diff
@@ -35,6 +38,22 @@
     private final List<Function<AtlasTransformerContext, JarEntryTransformer>> transformers = new ArrayList<>();
     private final List<JarFile> classpath = new ArrayList<>();
 
+    private final ExecutorService executorService;
+    private final boolean manageExecutor;
+
+    public Atlas(final ExecutorService executorService, final boolean manageExecutor) {
```
Comment (kashike) [inline src/main/java/org/cadixdev/atlas/Atlas.java:44]: I mentioned suggestions about this stuff to you - commenting to remind.
